version: '3.8'

services:
  cvision_web:
    container_name: cvision-web
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    build:
      context: .
      dockerfile: Dockerfile
    image: tannousgeagea/visionnest:latest
    restart: unless-stopped
    volumes:
      - .:/app
    network_mode: host
    ports:
      - "5173:5173"
